---

- name: roles demo 
  hosts: all
  gather_facts: false
  become: true

  roles:
    - common

  pre_tasks:
  - name: pre task
    debug:
      msg: "This is a pre task"

  tasks:
  - name: standard task
    debug:
      msg: "This is a standard task"

  post_tasks:
  - name: post task
    debug:
      msg: "This is a post task"

