---

- hosts: loadbalancer
  gather_facts: true

  tasks:
  - name: print os family, distribution name and distribution major version
    debug:
      msg: "os_family: {{ ansible_os_family }}; distribution_name: {{ ansible_distribution }}; distribution_major_version: {{ ansible_distribution_major_version }}"

  - name: print host's private ip assigned to eth0
    debug:
      msg: "ipv4: {{ ansible_eth0.ipv4.address }}"