---

- name: Showcase tags
  hosts: webservers
  gather_facts: true
  become: true
  tags: showcase

  tasks:
  - name: debug var1
    debug:
      var: ansible_default_ipv4.interface
    tags: debug

  - name: install ntp
    yum:
      name: ntp
      state: present
    tags:
      - install-ntp
      - ntp

  - name: start and enable ntp
    service:
      name: ntpd
      state: started
      enabled: true
    tags:
      - enable-ntp
      - ntp
    
  - name: check if ntp is running
    command: systemctl status ntpd
    tags:
      - check-ntp
      - ntp
    register: status
  
  - name: print ntp status
    debug:
      var: status.stdout_lines
    tags:
      - check-ntp
      - ntp